spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://pg:5432/studs
    username: s242322
  jpa:
    generate-ddl: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 42322

hunger-games:
  jwt:
    secret: wthisgoingon
    expirationMs: 86400000
