spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    username: test
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update